In [1]:
include("MCTS.jl")
include("value_iteration.jl")

Random.seed!(1234) 

TaskLocalRNG()

In [30]:
using Random
Random.seed!(24)  # reproducibility

gamma = 0.9
max_depth = 50
c_param = 1.2

S = 3
A = 2
H = 10

randMDP = random_MDP(H, S, A, γ=gamma, deterministic=true)
rollout_policy = random_rollout(randMDP)

optimal_policy = value_iteration(randMDP)[2]
rollout_policy = zeros(S,A)

for s in 1:S, a in 1:A
    rollout_policy[s,a] = (optimal_policy[s] == a)
end

config = MCTSConfig(randMDP, rollout_policy, max_depth = H, ucb, c_param)

counts = zeros(Int, length(randMDP.states))
tries = 100

for initial_state in 1:length(randMDP.states)
    for _ in 1:tries
        root = MCTSNode(initial_state)
        best_act = best_actions(root, config, 10000)
        if best_act == optimal_policy[initial_state]
            counts[initial_state] += 1
        end
    end
end

println("Accuracy per state: ", counts ./ tries)
println("Overall accuracy: ", sum(counts) / (tries * length(randMDP.states)))

MethodError: MethodError: no method matching random_MDP(::Int64, ::Int64, ::Int64; γ::Float64, deterministic::Bool)
The function `random_MDP` exists, but no method is defined for this combination of argument types.

Closest candidates are:
  random_MDP(::Int64, ::Int64; γ, deterministic)
   @ Main ~/Documents/2025/UCT-analysis-for-thesis/MDP.jl:10


In [15]:
optimal_policy

3-element Vector{Int64}:
 2
 2
 1

In [16]:
randMDP.dynamics

3×3×2 Array{Float64, 3}:
[:, :, 1] =
 0.0  0.0  0.0
 1.0  1.0  0.0
 0.0  0.0  1.0

[:, :, 2] =
 0.0  0.0  1.0
 1.0  0.0  0.0
 0.0  1.0  0.0

In [18]:
r = [randMDP.reward_function(s,a) for s in 1:3, a in 1:2]

3×2 Matrix{Float64}:
 -0.912923  -0.35417
  0.631621   0.796127
  1.43868   -1.17537

In [48]:
optimal_policy

3-element Vector{Int64}:
 2
 2
 1

In [31]:
randMDP.dynamics

3×3×2 Array{Float64, 3}:
[:, :, 1] =
 0.0  0.0  0.0
 1.0  1.0  0.0
 0.0  0.0  1.0

[:, :, 2] =
 0.0  0.0  1.0
 1.0  0.0  0.0
 0.0  1.0  0.0